"""tier2 quiverquant tables

Revision ID: 61801c568bd7
Revises: fa8667552e22
Create Date: 2026-05-10 04:40:40.333707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61801c568bd7'
down_revision: Union[str, None] = 'fa8667552e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('awarded_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_contracts_awarded_date'), 'government_contracts', ['awarded_date'], unique=False)
    op.create_index(op.f('ix_government_contracts_ticker'), 'government_contracts', ['ticker'], unique=False)
    op.create_table('lobbying_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('registrant', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('filed_date', sa.DateTime(), nullable=True),
    sa.Column('issue_codes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbying_disclosures_filed_date'), 'lobbying_disclosures', ['filed_date'], unique=False)
    op.create_index(op.f('ix_lobbying_disclosures_ticker'), 'lobbying_disclosures', ['ticker'], unique=False)
    op.create_table('campaign_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cycle', sa.String(length=10), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('donation_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_donations_donation_date'), 'campaign_donations', ['donation_date'], unique=False)
    op.create_index(op.f('ix_campaign_donations_member_id'), 'campaign_donations', ['member_id'], unique=False)
    op.create_index(op.f('ix_campaign_donations_ticker'), 'campaign_donations', ['ticker'], unique=False)
    op.create_index('ix_donations_member_ticker', 'campaign_donations', ['member_id', 'ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donations_member_ticker', table_name='campaign_donations')
    op.drop_index(op.f('ix_campaign_donations_ticker'), table_name='campaign_donations')
    op.drop_index(op.f('ix_campaign_donations_member_id'), table_name='campaign_donations')
    op.drop_index(op.f('ix_campaign_donations_donation_date'), table_name='campaign_donations')
    op.drop_table('campaign_donations')
    op.drop_index(op.f('ix_lobbying_disclosures_ticker'), table_name='lobbying_disclosures')
    op.drop_index(op.f('ix_lobbying_disclosures_filed_date'), table_name='lobbying_disclosures')
    op.drop_table('lobbying_disclosures')
    op.drop_index(op.f('ix_government_contracts_ticker'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_awarded_date'), table_name='government_contracts')
    op.drop_table('government_contracts')
    # ### end Alembic commands ###
