"""baseline schema

Revision ID: fa8667552e22
Revises: 
Create Date: 2026-05-07 01:42:17.077839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8667552e22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('chamber', sa.Enum('HOUSE', 'SENATE', name='chamber'), nullable=False),
    sa.Column('party', sa.Enum('DEMOCRAT', 'REPUBLICAN', 'INDEPENDENT', 'OTHER', name='party'), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('in_office', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('disclosure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_anomaly_count'), 'members', ['anomaly_count'], unique=False)
    op.create_index(op.f('ix_members_bioguide_id'), 'members', ['bioguide_id'], unique=True)
    op.create_index(op.f('ix_members_disclosure_count'), 'members', ['disclosure_count'], unique=False)
    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=50), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('is_ptr', sa.Boolean(), nullable=False),
    sa.Column('parsed', sa.Boolean(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_disclosures_filing_year'), 'disclosures', ['filing_year'], unique=False)
    op.create_index(op.f('ix_disclosures_is_ptr'), 'disclosures', ['is_ptr'], unique=False)
    op.create_index(op.f('ix_disclosures_member_id'), 'disclosures', ['member_id'], unique=False)
    op.create_index('ix_disclosures_member_year', 'disclosures', ['member_id', 'filing_year'], unique=False)
    op.create_index('ix_disclosures_ptr', 'disclosures', ['is_ptr', 'filing_year'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'BOND', 'MUTUAL_FUND', 'REAL_ESTATE', 'RETIREMENT', 'BANK_ACCOUNT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('value_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('income_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('income_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_disclosure_id'), 'assets', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('creditor', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('liability_type', sa.String(length=50), nullable=True),
    sa.Column('amount_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilities_disclosure_id'), 'liabilities', ['disclosure_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'SALE', 'EXCHANGE', name='transactiontype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('amount_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_disclosure_id'), 'transactions', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('computed_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_member_id'), 'anomalies', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_member_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ticker'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_disclosure_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_liabilities_disclosure_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_index(op.f('ix_assets_disclosure_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_disclosures_ptr', table_name='disclosures')
    op.drop_index('ix_disclosures_member_year', table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_member_id'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_is_ptr'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_filing_year'), table_name='disclosures')
    op.drop_table('disclosures')
    op.drop_index(op.f('ix_members_disclosure_count'), table_name='members')
    op.drop_index(op.f('ix_members_bioguide_id'), table_name='members')
    op.drop_index(op.f('ix_members_anomaly_count'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###

    # Alembic's autogenerate wrote the table drops above but not the enum
    # types those tables introduced, and Postgres keeps a type after the last
    # column using it is gone. So `downgrade base` left `chamber`, `party`,
    # `assettype` and `transactiontype` behind, and the next `upgrade` died on
    # `CREATE TYPE chamber` -- meaning `cli reset --yes`, which is exactly
    # `downgrade base` followed by `upgrade head`, dropped every table and then
    # could not rebuild. It left the database empty with no schema at all.
    #
    # SQLite has no native enum types and no DROP TYPE, so this is Postgres
    # only. Dropped in reverse creation order; IF EXISTS keeps the downgrade
    # re-runnable.
    if op.get_bind().dialect.name == "postgresql":
        for type_name in ("transactiontype", "assettype", "party", "chamber"):
            op.execute(f"DROP TYPE IF EXISTS {type_name}")
